// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKymE7gWKPUaB2cFLOgxvilbem01C0oU',
    appId: '1:690134956948:web:d1733718ccf518b2e9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    authDomain: 'reuse-hub-4b3f7.firebaseapp.com',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    measurementId: 'G-3CKRCENR13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDL_jN5ULzH1YQ9dcEPu9dSBLOINs1X68',
    appId: '1:690134956948:android:6544569e36bda56ae9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmfgvRW6xMZ-NogozSr0Hl9VXZ6j7iTc',
    appId: '1:690134956948:ios:ee4c5badce39272de9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    iosBundleId: 'com.example.software',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKymE7gWKPUaB2cFLOgxvilbem01C0oU',
    appId: '1:690134956948:web:da5e58f2f15251c8e9ad81',
    messagingSenderId: '690134956948',
    projectId: 'reuse-hub-4b3f7',
    authDomain: 'reuse-hub-4b3f7.firebaseapp.com',
    storageBucket: 'reuse-hub-4b3f7.firebasestorage.app',
    measurementId: 'G-HRXL3600TX',
  );

}